apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: detect-udp-connection
spec:
  message: "Alert: UDP Connection"
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: "*"
  network:
    matchProtocols:
    - protocol: udp
    action: Audit