apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: detect-tcp-connection
spec:
  message: "Alert: TCP Connection"
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: "*"
  network:
    matchProtocols:
    - protocol: tcp
    action: Audit