apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: detect-connection-from-directory
spec:
  message: "Alert: Suspicious Network Activity - Connection from suspicious directory"
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: "<node-name>"
  process:
    matchDirectories:
    - dir: /tmp/
      recursive: true
    - dir: /var/tmp/
      recursive: true
  network:
    matchProtocols:
    - protocol: tcp
    - protocol: udp
    action: Audit