apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: detect-udp-connection-from-directory
spec:
  message: "Alert: UDP Connection from suspicious directory"
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: "*"
  process:
    matchDirectories:
    - dir: /var/tmp/
      recursive: true
    action: Audit
  network:
    matchProtocols:
    - protocol: udp
    action: Audit