apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: detect-user-discovery
spec:
  message: "Alert: Suspicious Process Created - User/Account discovery"
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: "<node-name>"
  process:
    matchPaths:
    - path: /usr/bin/id
    - path: /usr/bin/whoami
    - path: /usr/bin/w
    - path: /usr/bin/who
    - path: /usr/bin/last
    - path: /usr/bin/lastlog
    - path: /usr/bin/groups
    - path: /usr/bin/getent
    action: Audit