apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: detect-user-login
spec:
  message: "Alert: User Login Process detected"
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: "*"
  process:
    matchPaths:
      - path: /usr/bin/login
    action: Audit
