apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: detect-file-creation
spec:
  message: "Alert: File Created in Suspicious Location"
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: "<node-name>"
  file:
    severity: 7
    matchDirectories:
    - dir: /tmp/
      recursive: true
    - dir: /var/tmp/
      recursive: true
    - dir: /etc/cron.d/
      recursive: true
    - dir: /etc/systemd/system/
      recursive: true
    action: Audit