apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: detect-file-creation
spec:
  message: "Alert: File Creation Tools Used"
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: "<node-name>"
  process:
    matchPaths:
    - path: /usr/bin/touch
    - path: /usr/bin/cp
    - path: /usr/bin/mv
    - path: /usr/bin/tee
    - path: /usr/bin/dd
    - path: /usr/bin/xxd
    action: Audit