apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: detect-kubearmor-binary-tamper
spec:
  message: "Alert: KubeArmor binary tamper detected"
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: "*"
  file:
    matchDirectories:
    - dir: /opt/kubearmor/
      recursive: true
    matchPaths:
    - path: /usr/local/bin/kubearmor
    action: Audit