apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: detect-service-activity
spec:
  message: "Alert: Service activity detected"
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: "*"
  file:
    matchDirectories:
    - dir: /etc/systemd/system/
      recursive: true
    - dir: /usr/lib/systemd/system/
      recursive: true
    - dir: /run/systemd/system/
      recursive: true
    action: Audit