apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: block-network-discovery-tools
spec:
  message: "Alert: Network Discovery Tools Blocked"
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: "*"
  process:
    matchPaths:
    - path: /usr/bin/ss
    - path: /usr/bin/ip
    action: Block