apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: block-process-exec-on-sensitive-directory
spec:
  message: "Alert: Process Execution on Sensitive Directory"
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: "*"
  file:
    matchDirectories:
    - dir: /var/tmp/
      recursive: true  
  process:
    matchPaths:
    - path: /usr/bin/gpg
    - path: /usr/bin/gpg-agent
  action:
    Block