apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: detect-encryption-tools
spec:
  message: "Alert: Suspicious Process Created - Encryption Tools"
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: "*"
  process:
    matchPaths:
    - path: /usr/bin/gpg
    - path: /usr/bin/gpg-agent
    - path: /usr/bin/gpg-connect-agent
    action: Audit