apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: detect-pkg-manager-usage
spec:
  message: "Alert: Suspicious Process Created - Package Manager Usage"
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: "*"
  process:
    matchPaths:
    - path: /usr/bin/apt
    - path: /usr/bin/apt-get
    - path: /usr/bin/snap
    - path: /usr/bin/dpkg
    action: Audit