apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: detect-compiler-execution
spec:
  message: "Alert: Suspicious Process Created - Compiler Execution"
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: "*"
  process:
    matchDirectories:
    - dir: /usr/lib/go/
      recursive: true
    - dir: /usr/lib/gcc/
      recursive: true
    action: Audit