apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: detect-process-and-service-termination-tools
spec:
  message: "Alert: Process or Service Termination Tool Executed"
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: "*"
  process:
    matchPaths:
    - path: /usr/bin/kill
    - path: /usr/bin/pkill
    - path: /usr/bin/killall
    - path: /usr/sbin/rfkill
    action: Audit