apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: detect-process-discovery
spec:
  message: "Alert: Suspicious Process Created - Process discovery"
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: "<node-name>"
  process:
    matchPaths:
    - path: /usr/bin/ps
    action: Audit