apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: detect-compiler-execution
spec:
  message: "Alert: Suspicious Process Created - Compiler Execution"
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: "*"
  process:
    matchPaths:
      - path: /usr/bin/cc
      - path: /usr/bin/clang
      - path: /usr/bin/gcc
      - path: /usr/bin/g++
      - path: /usr/bin/go
      - path: /usr/bin/rustc
    action: Block
