apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: detect-file-operation-in-sensitive-directory
spec:
  message: "Alert: File operation detected in sensitive directory"
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: "*"
  file:
    matchDirectories:
    - dir: /tmp/
      recursive: true
    - dir: /var/tmp/
      recursive: true
    - dir: /etc/cron.d/
      recursive: true
    - dir: /etc/cron.daily/
      recursive: true
    - dir: /var/spool/cron/
      recursive: true
    - dir: /etc/systemd/system/
      recursive: true
    action: Audit