apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: detect-file-deletion
spec:
  message: "Alert: File Deleted in Sensitive Location"
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: "<node-name>"
  file:
    matchPaths:
    - path: /root/.ssh/authorized_keys
    - path: /root/.ssh/id_rsa
    - path: /root/.bash_history
    - path: /etc/passwd
    - path: /etc/shadow
    - path: /etc/group
    - path: /etc/sudoers
    matchDirectories:
    - dir: /etc/cron.d/
      recursive: true
    - dir: /etc/systemd/system/
      recursive: true
    - dir: /var/log/
      recursive: true
    - dir: /home/
      recursive: true
    action: Audit